services:
  producer:
    build: 
      context: ./worker-service/producers
      dockerfile: Dockerfile
    networks:
      - worker
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis

  consumer:
    build: 
      context: ./worker-service/consumers
      dockerfile: Dockerfile
    networks:
      - worker
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
    deploy:
      replicas: 2

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - worker

  board:
    build: 
      context: ./worker-service/board
      dockerfile: Dockerfile
    networks:
      - worker
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
    ports:
      - 3000:3000

networks:
  worker:
    driver: bridge
