services:
  producer:
    build: 
      context: ./task-service/producers
      dockerfile: Dockerfile
    networks:
      - task-network
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis

  worker:
    build: 
      context: ./task-service/workers
      dockerfile: Dockerfile
    networks:
      - task-network
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis

  listener:
    build: 
      context: ./task-service/listeners
      dockerfile: Dockerfile
    networks:
      - task-network
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis


  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - task-network

networks:
  task-network:
    driver: bridge
